steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Create assets folder
    run: mkdir -p ./assets

  - name: Fetch TryHackMe Badge
    uses: DhanushNehru/tryhackme-badge-action-workflow@v1.0
    with:
      image_path: './assets/tryhackme-badge.png'
      username: 'yg3721'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
